name: Node.js CI

on:
  push:
    paths:
      - 'chapter-3/**'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
        working-directory: chapter-3
      - run: npm run build --if-present
        working-directory: chapter-3
      - run: npm start &
        working-directory: chapter-3
        env:
          NODE_ENV: ci
      - run: sleep 1
        working-directory: chapter-3
      - run: npm test
        working-directory: chapter-3
        env:
          NODE_ENV: ci